// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDan_axsmZEFCSmRQKMgLdJ0cf_B1KExqA',
    appId: '1:493852177514:web:3428e7fb200e4157480613',
    messagingSenderId: '493852177514',
    projectId: 'chatify-f26dc',
    authDomain: 'chatify-f26dc.firebaseapp.com',
    storageBucket: 'chatify-f26dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBViOji0q7pdIEuc7vYbkkT20-KPbCvBUk',
    appId: '1:493852177514:android:462ea850000b61d1480613',
    messagingSenderId: '493852177514',
    projectId: 'chatify-f26dc',
    storageBucket: 'chatify-f26dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-EQQkzWShIBHCnWiGcAVxE9iy6GlbIk',
    appId: '1:493852177514:ios:fcc7def44be1c973480613',
    messagingSenderId: '493852177514',
    projectId: 'chatify-f26dc',
    storageBucket: 'chatify-f26dc.appspot.com',
    iosBundleId: 'com.example.chatify',
  );
}
