// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7-JT6K1u_6L-7ex_rAFFME_icgCJHE0k',
    appId: '1:488122836155:web:65d6a4ab608e782a08f59e',
    messagingSenderId: '488122836155',
    projectId: 'chatify-41173',
    authDomain: 'chatify-41173.firebaseapp.com',
    storageBucket: 'chatify-41173.appspot.com',
    measurementId: 'G-P0JRJ7FGMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhkEz76kPxRCCAqotUXc3HOccpV7mygi0',
    appId: '1:488122836155:android:6273f374d7e2d02908f59e',
    messagingSenderId: '488122836155',
    projectId: 'chatify-41173',
    storageBucket: 'chatify-41173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvnE1qKayop59Z8ihcCCYKM8XEe7tAxtM',
    appId: '1:488122836155:ios:dfb14a447bf2c5ae08f59e',
    messagingSenderId: '488122836155',
    projectId: 'chatify-41173',
    storageBucket: 'chatify-41173.appspot.com',
    iosBundleId: 'com.example.chatify',
  );
}
